/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

/**
 *
 * @author LENOVO
 */
import javax.swing.*;
import javax.swing.Timer;
import java.text.SimpleDateFormat;
import java.util.Date;


public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    private JTextField[] quantityFields;
    private JCheckBox[] selectionCheckboxes;
    
    public menu() {
        initComponents();
        // Format tanggal dan waktu
SimpleDateFormat tanggalFormat = new SimpleDateFormat("dd-MM-yyyy");
SimpleDateFormat waktuFormat = new SimpleDateFormat("HH:mm:ss");

// Timer untuk memperbarui waktu setiap detik
Timer timer = new Timer(1000, e -> {
    Date sekarang = new Date();
    textFieldTanggal.setText(tanggalFormat.format(sekarang)); // Set tanggal
    textFieldWaktu.setText(waktuFormat.format(sekarang)); // Set waktu
});

// Mulai timer
timer.start();

        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkNasiGoreng = new javax.swing.JCheckBox();
        jSpinnerNasiGoreng = new javax.swing.JSpinner();
        jSpinnerBakso = new javax.swing.JSpinner();
        chkBakso = new javax.swing.JCheckBox();
        jSpinnerNasiUduk = new javax.swing.JSpinner();
        chkNasiUduk = new javax.swing.JCheckBox();
        chkBatagor = new javax.swing.JCheckBox();
        jSpinnerBatagor = new javax.swing.JSpinner();
        jSpinnerCireng = new javax.swing.JSpinner();
        chkCireng = new javax.swing.JCheckBox();
        jSpinnerAyamGeprek = new javax.swing.JSpinner();
        chkAyamGeprek = new javax.swing.JCheckBox();
        jSpinnerBuburAyam = new javax.swing.JSpinner();
        chkBuburAyam = new javax.swing.JCheckBox();
        jSpinnerSeblak = new javax.swing.JSpinner();
        chkSeblak = new javax.swing.JCheckBox();
        chkMieGoreng = new javax.swing.JCheckBox();
        jSpinnerMieGoreng = new javax.swing.JSpinner();
        jSpinnerMieRebus = new javax.swing.JSpinner();
        chkMieRebus = new javax.swing.JCheckBox();
        chkAyamKatsu = new javax.swing.JCheckBox();
        jSpinnerAyamKatsu = new javax.swing.JSpinner();
        chkNasiPadang = new javax.swing.JCheckBox();
        jSpinnerNasiPadang = new javax.swing.JSpinner();
        jSpinnerKare = new javax.swing.JSpinner();
        chkKare = new javax.swing.JCheckBox();
        chkSushi = new javax.swing.JCheckBox();
        jSpinnerSushi = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPajak = new javax.swing.JTextField();
        txtTotalHargaMakanan = new javax.swing.JTextField();
        txtTotalKeseluruhan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textFieldWaktu = new javax.swing.JTextField();
        textFieldTanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html> Ayo Temukan<br> Makanan Kesukaanmu</html> ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        chkNasiGoreng.setText("Beli Ini");
        chkNasiGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasiGorengActionPerformed(evt);
            }
        });
        jPanel1.add(chkNasiGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        jPanel1.add(jSpinnerNasiGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 60, 20));
        jPanel1.add(jSpinnerBakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 60, 20));

        chkBakso.setText("Beli Ini");
        chkBakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBaksoActionPerformed(evt);
            }
        });
        jPanel1.add(chkBakso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));
        jPanel1.add(jSpinnerNasiUduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 60, 20));

        chkNasiUduk.setText("Beli Ini");
        chkNasiUduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasiUdukActionPerformed(evt);
            }
        });
        jPanel1.add(chkNasiUduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        chkBatagor.setText("Beli Ini");
        chkBatagor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBatagorActionPerformed(evt);
            }
        });
        jPanel1.add(chkBatagor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));
        jPanel1.add(jSpinnerBatagor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 60, 20));
        jPanel1.add(jSpinnerCireng, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 60, 20));

        chkCireng.setText("Beli Ini");
        chkCireng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCirengActionPerformed(evt);
            }
        });
        jPanel1.add(chkCireng, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, -1, -1));
        jPanel1.add(jSpinnerAyamGeprek, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 60, 20));

        chkAyamGeprek.setText("Beli Ini");
        chkAyamGeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyamGeprekActionPerformed(evt);
            }
        });
        jPanel1.add(chkAyamGeprek, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, -1, -1));
        jPanel1.add(jSpinnerBuburAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 60, 20));

        chkBuburAyam.setText("Beli Ini");
        chkBuburAyam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBuburAyamActionPerformed(evt);
            }
        });
        jPanel1.add(chkBuburAyam, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, -1, -1));
        jPanel1.add(jSpinnerSeblak, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 60, 20));

        chkSeblak.setText("Beli Ini");
        chkSeblak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSeblakActionPerformed(evt);
            }
        });
        jPanel1.add(chkSeblak, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        chkMieGoreng.setText("Beli Ini");
        chkMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieGorengActionPerformed(evt);
            }
        });
        jPanel1.add(chkMieGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));
        jPanel1.add(jSpinnerMieGoreng, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, 60, 20));
        jPanel1.add(jSpinnerMieRebus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 60, 20));

        chkMieRebus.setText("Beli Ini");
        chkMieRebus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMieRebusActionPerformed(evt);
            }
        });
        jPanel1.add(chkMieRebus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, -1, -1));

        chkAyamKatsu.setText("Beli Ini");
        chkAyamKatsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyamKatsuActionPerformed(evt);
            }
        });
        jPanel1.add(chkAyamKatsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, -1, -1));
        jPanel1.add(jSpinnerAyamKatsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 60, 20));

        chkNasiPadang.setText("Beli Ini");
        chkNasiPadang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNasiPadangActionPerformed(evt);
            }
        });
        jPanel1.add(chkNasiPadang, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));
        jPanel1.add(jSpinnerNasiPadang, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, 60, 20));
        jPanel1.add(jSpinnerKare, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 60, 20));

        chkKare.setText("Beli Ini");
        chkKare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkKareActionPerformed(evt);
            }
        });
        jPanel1.add(chkKare, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, -1, -1));

        chkSushi.setText("Beli Ini");
        chkSushi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSushiActionPerformed(evt);
            }
        });
        jPanel1.add(chkSushi, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, -1, -1));
        jPanel1.add(jSpinnerSushi, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 60, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Group 97.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 100, 910, -1));

        btnReset.setBackground(new java.awt.Color(255, 75, 58));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 75, 58));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, -1, -1));

        btnExit.setBackground(new java.awt.Color(255, 75, 58));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 75, 58));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Bayar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 75, 58));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pajak");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Harga Makanan");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Keseluruhan");

        txtPajak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPajakActionPerformed(evt);
            }
        });

        txtTotalHargaMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaMakananActionPerformed(evt);
            }
        });

        txtTotalKeseluruhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalKeseluruhanActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rincian"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPajak)
                            .addComponent(txtTotalHargaMakanan)
                            .addComponent(txtTotalKeseluruhan)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPajak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTotalHargaMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalKeseluruhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, 260, 490));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hai Admin Selamat Datang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 75, 58));

        textFieldWaktu.setBackground(new java.awt.Color(255, 75, 58));
        textFieldWaktu.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        textFieldWaktu.setForeground(new java.awt.Color(255, 255, 255));
        textFieldWaktu.setBorder(null);
        textFieldWaktu.setCaretColor(new java.awt.Color(255, 75, 58));

        textFieldTanggal.setBackground(new java.awt.Color(255, 75, 58));
        textFieldTanggal.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        textFieldTanggal.setForeground(new java.awt.Color(255, 255, 255));
        textFieldTanggal.setBorder(null);
        textFieldTanggal.setCaretColor(new java.awt.Color(255, 75, 58));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(924, Short.MAX_VALUE)
                .addComponent(textFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasiGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNasiGorengActionPerformed

    private void chkBaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBaksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBaksoActionPerformed

    private void chkNasiUdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasiUdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNasiUdukActionPerformed

    private void chkBatagorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBatagorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBatagorActionPerformed

    private void chkCirengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCirengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCirengActionPerformed

    private void chkAyamGeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyamGeprekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAyamGeprekActionPerformed

    private void chkBuburAyamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBuburAyamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBuburAyamActionPerformed

    private void chkSeblakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSeblakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSeblakActionPerformed

    private void chkMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMieGorengActionPerformed

    private void chkMieRebusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMieRebusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMieRebusActionPerformed

    private void chkAyamKatsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyamKatsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAyamKatsuActionPerformed

    private void chkNasiPadangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasiPadangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNasiPadangActionPerformed

    private void chkKareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkKareActionPerformed

    private void chkSushiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSushiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSushiActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    jSpinnerNasiGoreng.setValue(0);
    jSpinnerBakso.setValue(0);
    jSpinnerNasiUduk.setValue(0);
    jSpinnerBatagor.setValue(0);
    jSpinnerCireng.setValue(0);
    jSpinnerAyamGeprek.setValue(0);
    jSpinnerBuburAyam.setValue(0);
    jSpinnerSeblak.setValue(0);
    jSpinnerMieGoreng.setValue(0);
    jSpinnerMieRebus.setValue(0);
    jSpinnerAyamKatsu.setValue(0);
    jSpinnerNasiPadang.setValue(0);
    jSpinnerKare.setValue(0);
    jSpinnerSushi.setValue(0);
    
    chkNasiGoreng.setSelected(false);
    chkBakso.setSelected(false);
    chkNasiUduk.setSelected(false);
    chkBatagor.setSelected(false);
    chkCireng.setSelected(false);
    chkAyamGeprek.setSelected(false);
    chkBuburAyam.setSelected(false);
    chkSeblak.setSelected(false);
    chkMieGoreng.setSelected(false);
    chkMieRebus.setSelected(false);
    chkAyamKatsu.setSelected(false);
    chkNasiPadang.setSelected(false);
    chkKare.setSelected(false);
    chkSushi.setSelected(false);
    // Mengosongkan
    txtTotalHargaMakanan.setText("");
    txtPajak.setText("");
    txtTotalKeseluruhan.setText("");

    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         double totalHarga = 0;
         double pajak = 0.1; // Misal, pajak 10%

        // Mendapatkan nilai dari masing-masing makanan
        if (chkNasiGoreng.isSelected()) {
            int qty = (int) jSpinnerNasiGoreng.getValue();
            totalHarga += qty * 10000;
        }
        if (chkBakso.isSelected()) {
            int qty = (int) jSpinnerBakso.getValue();
            totalHarga += qty * 10000;
        }
        if (chkNasiUduk.isSelected()) {
            int qty = (int) jSpinnerNasiUduk.getValue();
            totalHarga += qty * 15000;
        }
        if (chkBatagor.isSelected()) {
            int qty = (int) jSpinnerBatagor.getValue();
            totalHarga += qty * 5000;
        }
        if (chkCireng.isSelected()) {
            int qty = (int) jSpinnerCireng.getValue();
            totalHarga += qty * 5000;
        }
        if (chkAyamGeprek.isSelected()) {
            int qty = (int) jSpinnerAyamGeprek.getValue();
            totalHarga += qty * 10000;
        }
        if (chkBuburAyam.isSelected()) {
            int qty = (int) jSpinnerBuburAyam.getValue();
            totalHarga += qty * 8000;
        }
        if (chkSeblak.isSelected()) {
            int qty = (int) jSpinnerSeblak.getValue();
            totalHarga += qty * 15000;
        }
        if (chkMieGoreng.isSelected()) {
            int qty = (int) jSpinnerMieGoreng.getValue();
            totalHarga += qty * 10000;
        }
        if (chkMieRebus.isSelected()) {
            int qty = (int) jSpinnerMieRebus.getValue();
            totalHarga += qty * 10000;
        }
        if (chkAyamKatsu.isSelected()) {
            int qty = (int) jSpinnerAyamKatsu.getValue();
            totalHarga += qty * 10000;
        }
        if (chkNasiPadang.isSelected()) {
            int qty = (int) jSpinnerNasiPadang.getValue();
            totalHarga += qty * 10000;
        }
        if (chkKare.isSelected()) {
            int qty = (int) jSpinnerKare.getValue();
            totalHarga += qty * 10000;
        }
        if (chkSushi.isSelected()) {
            int qty = (int) jSpinnerSushi.getValue();
            totalHarga += qty * 10000;
        }

        // Hitung pajak dan total keseluruhan
        double totalPajak = totalHarga * pajak;
        double totalKeseluruhan = totalHarga + totalPajak;

        // Set nilai ke tampilan
        txtPajak.setText(String.format("Rp%.2f", totalPajak));
        txtTotalHargaMakanan.setText(String.format("Rp%.2f", totalHarga));
        txtTotalKeseluruhan.setText(String.format("Rp%.2f", totalKeseluruhan));
        
        jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:                                        
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           // Membuat instance dari GUI Pembayaran
    Pembayaran pembayaran = new Pembayaran();

    // Menampilkan GUI Pembayaran
    pembayaran.setVisible(true);

    // Menutup GUI Pemesanan saat ini
    this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtPajakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPajakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPajakActionPerformed

    private void txtTotalHargaMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaMakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaMakananActionPerformed

    private void txtTotalKeseluruhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalKeseluruhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalKeseluruhanActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JCheckBox chkAyamGeprek;
    private javax.swing.JCheckBox chkAyamKatsu;
    private javax.swing.JCheckBox chkBakso;
    private javax.swing.JCheckBox chkBatagor;
    private javax.swing.JCheckBox chkBuburAyam;
    private javax.swing.JCheckBox chkCireng;
    private javax.swing.JCheckBox chkKare;
    private javax.swing.JCheckBox chkMieGoreng;
    private javax.swing.JCheckBox chkMieRebus;
    private javax.swing.JCheckBox chkNasiGoreng;
    private javax.swing.JCheckBox chkNasiPadang;
    private javax.swing.JCheckBox chkNasiUduk;
    private javax.swing.JCheckBox chkSeblak;
    private javax.swing.JCheckBox chkSushi;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAyamGeprek;
    private javax.swing.JSpinner jSpinnerAyamKatsu;
    private javax.swing.JSpinner jSpinnerBakso;
    private javax.swing.JSpinner jSpinnerBatagor;
    private javax.swing.JSpinner jSpinnerBuburAyam;
    private javax.swing.JSpinner jSpinnerCireng;
    private javax.swing.JSpinner jSpinnerKare;
    private javax.swing.JSpinner jSpinnerMieGoreng;
    private javax.swing.JSpinner jSpinnerMieRebus;
    private javax.swing.JSpinner jSpinnerNasiGoreng;
    private javax.swing.JSpinner jSpinnerNasiPadang;
    private javax.swing.JSpinner jSpinnerNasiUduk;
    private javax.swing.JSpinner jSpinnerSeblak;
    private javax.swing.JSpinner jSpinnerSushi;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textFieldTanggal;
    private javax.swing.JTextField textFieldWaktu;
    private javax.swing.JTextField txtPajak;
    private javax.swing.JTextField txtTotalHargaMakanan;
    private javax.swing.JTextField txtTotalKeseluruhan;
    // End of variables declaration//GEN-END:variables
}
